version: '3.6'
services:
  api:
    build:
      context: api
      target: developer
    volumes:
      - ./api:/app
    environment:
      - XDEBUG_CONFIG=idekey=api remote_enable=1 remote_host=${DOCKER_HOST_IP}
    env_file:
      - api/.env
    ports:
      - 8000:8000
  web:
    build:
      context: web
      target: developer
    volumes:
      - ./web:/app
    ports:
      - 80:3000
